### ISSUE TITLE
Error parsing configuration file

### ISSUE THREAD

**Issue by naatumach** [Hirse/brackets-prettier#5]
I just installed Prettier for Brackets and got this error. 
Error Formatting File - Undefined.

"Unable to load one of the modules: C:/Users/<user>/AppData/Roaming/Brackets/extensions/user/hirse.brackets-prettier/node/domain, reason: Unexpected token *"

**Comment by naatumach** [comment]
I think its because i am trying to format an HTML file. My bad. Sorry.

**Comment by ordinarysamar** [comment]
I have the same problem but this is for all the files even the files listed by the website....
This is not an HTML problem i guess, I think there are dependencies that we have to install, as due to the https://registry.brackets.io/ is not working properly and the Brackets is discontinued by adobe. I think there must be a break out through this....

**Comment by Anke** [comment]
Same problem with a CSS file
